# Rain Prediction in Australia

## Content
1. [Import Libraries](#1)
2. [Data Content](#2)
3. [Read Data and Analysis](#3)
4. [Preprocessing](#4)
  * Missing Value
  * Encoding Categorical Features
  * Scaling
  * Train/Test Split
5. [Modelling](#5)  
  * Logistic Regression
  * K-NN
6. [Evaluation of Models](#6)
  * Confusion Matrix
  * Accuracy

<a id='1'></a>
### Import Libraries

In [1]:
import numpy as np
import pandas as pd 
import missingno as msno
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix , accuracy_score
import warnings
warnings.filterwarnings("ignore")

<a id='2'></a>
### Data Content

* Date : The date of observation
* Location : The common name of the location of the weather station
* MinTemp : The minimum temperature in degrees celsius
* MaxTemp : The maximum temperature in degrees celsius
* Rainfall : The amount of rainfall recorded for the day in mm
* Evaporation : The so-called Class A pan evaporation (mm) in the 24 hours to 9am
* Sunshine : The number of hours of bright sunshine in the day
* WindGustDir : The direction of the strongest wind gust in the 24 hours to midnight
* WindGustSpeed : The speed (km/h) of the strongest wind gust in the 24 hours to midnight
* WindDir9am : Direction of the wind at 9am
* WindDir3pm : Direction of the wind at 3pm
* WindSpeed9am : Speed of the wind at 9am
* WindSpeed3am : Speed of the wind at 3pm
* Humidity9am : Humidty at 9am
* Humidity3pm : Humidty at 3pm
* Pressure9am : Pressure at 9am
* Pressure3pm : Pressure at 3pm
* Cloud9am : Cloud at 9am
* Cloud3pm : Cloud at 3pm
* Temp9am : Temp at 9am
* Temp3pm : Temp at 3pm
* RainToday : Did it rain today?
* RainTomorrow : Did it rain the next day?

<a id='3'></a>
### Read Data and Analysis

In [4]:
df = pd.read_csv("C:\\Users\\GulerKandeger\\Desktop\\Machine Learning\\WeatherAUS.csv")
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No